# Generated by Django 5.0.1 on 2024-01-31 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created'], 'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
    ]
