# Generated by Django 5.0.1 on 2024-01-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='numero_ediciones',
            field=models.IntegerField(default=0),
        ),
    ]
