# Generated by Django 5.0.1 on 2024-01-13 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_numero_ediciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='numero_ediciones',
        ),
    ]
