# Generated by Django 5.0.1 on 2024-01-25 16:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comments_post_alter_comments_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
